name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  erlang-26:

    runs-on: ubuntu-latest

    container:
      image: erlang:26

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 test
      - name: dialyzer
        run: rebar3 dialyzer

  erlang-28:

    runs-on: ubuntu-latest

    container:
      image: erlang:28

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 test
      - name: dialyzer
        run: rebar3 dialyzer
